server:
  port: 8081
spring:
  application:
    name: boke
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/boke?useSSL=false&serverTimezone=UTC
    username: root
    password: 1313
  redis:
    host: 127.0.0.1
    port: 6379
#    password: 123321
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    database: 0

  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.boke.entity # 别名扫描包
logging:
  level:
    com.boke: debug

# 百度AI内容安全API
baidu:
  ai:
    api-key: tp-cgcvso1qz398xeor526i96tpaj21y9q9lf7qx6
    secret-key: wendao
